### ISSUE TITLE
Firmware files

### ISSUE THREAD

**Issue by Tuom** [scarface-one/firmware-motorola-potter#1]
Hi, I am trying to install postmarket OS on my Moto G5 Plus. It works, but display is black.
I was wondering where did you get these firmware files. I found this in crdroid repo https://github.com/crdroidandroid/android_vendor_motorola_potter/tree/8.1/proprietary/etc/firmware
It differs from yours. Do you think that I can try those?

I have XT1685 model with Tianma panel.

**Comment by SirSireesh** [comment]
The firmware was pulled from an XT1686. Perhaps the XT1685 runs slightly different firmware. But the black screen could be caused by a variety of issues, firmware would be an unlikely suspect for me.

**Comment by Tuom** [comment]
Thanks for your answer. Are you still using postmarket os on this phone? Just wondering if the current version works on your model. I tried few things, but nothing helped yet. If you have some hints for me what should I try, it would be really helpful.
